index:
    path: /
    controller: App\Controller\MainController::Overview

fixer:
    path: /fixer/{fxid}
    controller: App\Controller\MainController::fixerview

fixers:
    path: /fixers
    controller: App\Controller\MainController::fixers



repair_new:
    path: /repair/new
    controller: App\Controller\RepairController::new

repair_edit:
    path: /repair/edit/{rpid}/{step}
    controller: App\Controller\RepairController::edit
    defaults:
      rpid: -1
      step: client

repair_update:
    path: /repair/updatescript/{rpid}/{step}
    controller: App\Controller\RepairController::update
    defaults:
      rpid: -1
      step: client

fixer_follow:
     path: /fixer/follow/{fxid}/{rpid}
     controller: App\Controller\FixerController::follow


fixer_view:
     path: /fixer/view/{fxid}/{rpid}
     controller: App\Controller\FixerController::view
